### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by janowsiany**
Configure tests environment and add simple tests for no-console rule.

### CODE REVIEW

**Comment by janowsiany** [comment]
Should switch to mocha as jest doesn't do well with `expected` and `actual`?
https://github.com/facebook/jest/issues/3173

Perhaps i can use [ava](https://github.com/avajs/ava)

**Comment by MacRusher** [comment]
If ESLint tests can be run concurrently (and I believe they can) then AVA may be a really good choice.

Using Jest as a runner if we're not using anything special from it and it it has this know bug may not be a good idea. You can always just run `node testFile.js` :)

**Review by MacRusher — APPROVED** [review]

**Review by radekmie — APPROVED** [review]

**Review by MichalW — APPROVED** [review]

**Comment by kentcdodds** [comment]
FYI, I'm currently working on making Jest behave better with this (as referenced facebook/jest#3173). Hopefully in the next version of Jest will have the better messaging.

> If ESLint tests can be run concurrently (and I believe they can) then AVA may be a really good choice.

Note that Jest _also_ runs tests concurrently :)

**Comment by janowsiany** [comment]
Thanks for your attention! If you will need any help with this PR, feel free to ping me!

**Review by radekmie — APPROVED** [review]
Long time, huh?

**Pull request merged**
